- name: "get services current status"
  win_service:
    name: w3svc
  register: services_status
#  with_items: "{{ services }}"
  when: 
    - comp == "app2"

- name: "print the current status of services"
  debug:
    msg: "service {{ item.name }} is in {{ item.state }} state"
  loop: "{{ services_status.results }}"
  when: "item.state is defined"
